management.endpoints.web.exposure.include: hystrix.stream
spring.cloud.compatibility-verifier.enabled: false
#Name of the application
spring:
  application:
    name: student

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

instance:
  hostname: localhost
server:
  port: 8930